### ISSUE TITLE
Instructions for Mac users

### ISSUE THREAD

**Issue by awead** [samvera-deprecated/sufia-vagrant#4]
Those of us, including me, that are unfamiliar with vagrant and VirtualBox need some education.

**Comment by no-reply** [comment]
Thanks.  I added some (probably insufficient) vagrant install instructions for Windows, Mac, and Linux.  Would be great if people could try it out and help me fill in the details.

PRs are, of course, accepted; but if you can also feel free to dump any knowledge or issues about vagrant installing here, and I'll try to get it into the README in a way that makes sense.
